export const PAYMENT_PROVIDERS = [
  {
    id: "mtn_momo",
    name: "MTN Mobile Money",
    type: "mobile_money",
    enabled: true,
    demoMode: !import.meta.env.VITE_MTN_MOMO_SUBSCRIPTION_KEY,
    countries: ["CM", "CI", "GH", "UG", "RW"],
    currencies: ["XAF", "XOF", "GHS", "UGX", "RWF"],
    supportsRefunds: true,
    logoText: "MTN MoMo",
    color: "bg-yellow-500",
  },
  {
    id: "orange_money",
    name: "Orange Money",
    type: "mobile_money",
    enabled: true,
    demoMode: !import.meta.env.VITE_ORANGE_MONEY_CLIENT_ID,
    countries: ["CM", "CI", "SN", "SN", "ML"],
    currencies: ["XAF", "XOF"],
    supportsRefunds: true,
    logoText: "Orange Money",
    color: "bg-orange-500",
  },
  {
    id: "cinetpay",
    name: "CinetPay",
    type: "gateway",
    enabled: true,
    demoMode: !import.meta.env.VITE_CINETPAY_API_KEY,
    countries: ["CM", "CI", "SN", "ML", "TG"],
    currencies: ["XAF", "XOF", "CDF", "GNF"],
    supportsRefunds: false,
    logoText: "CinetPay",
    color: "bg-emerald-500",
  },
  {
    id: "flutterwave",
    name: "Flutterwave",
    type: "gateway",
    enabled: true,
    demoMode: !import.meta.env.VITE_FLUTTERWAVE_PUBLIC_KEY,
    countries: ["NG", "GH", "KE", "ZA", "UG", "RW", "CM", "CI"],
    currencies: ["NGN", "GHS", "KES", "ZAR", "UGX", "RWF", "XAF", "XOF", "USD"],
    supportsRefunds: true,
    logoText: "Flutterwave",
    color: "bg-amber-600",
  },
  {
    id: "manual_demo",
    name: "Manual Payment",
    type: "manual",
    enabled: true,
    demoMode: true,
    countries: ["GLOBAL"],
    currencies: ["XAF", "USD", "EUR"],
    supportsRefunds: true,
    logoText: "Cash/Manual",
    color: "bg-slate-600",
  }
];