import { USER_ROLES, normalizeRole, isAdminRole } from "./userRoles"; // Standardized import

export const ROLE_PERMISSIONS = {
  [USER_ROLES.NORMAL_USER]: [
    "browse_events",
    "buy_ticket",
    "post_memory",
    "like",
    "comment",
    "share",
    "view_gallery",
    "browse_marketplace",
    "buy_marketplace_item",
    "book_vendor",
    "manage_profile",
    "view_qr",
    "post_memories",
    "review_vendor",
    "view_availability",
    "view_availability",
    "view_vendor_crm",
    "manage_leads",
    "manage_customers",
    "manage_customer_notes",
    "preview_ai_storefront_theme",
    "upload_brand_assets",
    "create_marketplace_listing",
    "manage_own_storefront",
    "create_marketplace_product",
    "edit_own_marketplace_product",
    "edit_storefront_theme",
    "publish_storefront",
    "view_storefront_analytics",
    "sell_marketplace_item",
    "manage_own_listing",
    "view_vendor_wallet",
    "view_vendor_earnings",
    "manage_vendor_portfolio",
    "view_vendor_reviews",
    "manage_own_marketplace_profile",
    "create_event",
    "create_events",
    "manage_own_events",
    "manage_event",
    "manage_guests",
    "make_payment",
    "submit_payment_proof",
    "view_payment_receipt",
    "view_own_payments"
  ],
  [USER_ROLES.PRO_USER]: [
    "browse_events",
    "buy_ticket",
    "post_memory",
    "like",
    "comment",
    "share",
    "view_gallery",
    "browse_marketplace",
    "buy_marketplace_item",
    "book_vendor",
    "premium_features",
    "premium_templates",
    "advanced_gallery",
    "priority_support",
    "manage_profile",
    "view_qr",
    "post_memories",
    "review_vendor",
    "view_vendor_crm",
    "manage_leads",
    "manage_customers",
    "manage_customer_notes",
    "create_invoices",
    "manage_followups",
    "preview_ai_storefront_theme",
    "upload_brand_assets",
    "generate_ai_storefront_theme",
    "publish_ai_storefront_theme",
    "customize_storefront_theme",
    "create_marketplace_listing",
    "manage_own_storefront",
    "create_marketplace_product",
    "edit_own_marketplace_product",
    "edit_storefront_theme",
    "publish_storefront",
    "view_storefront_analytics",
    "sell_marketplace_item",
    "manage_own_listing",
    "view_vendor_wallet",
    "view_vendor_earnings",
    "manage_vendor_portfolio",
    "view_vendor_reviews",
    "manage_own_marketplace_profile",
    "create_event",
    "create_events",
    "manage_own_events",
    "manage_event",
    "manage_guests",
    "make_payment",
    "submit_payment_proof",
    "view_payment_receipt",
    "view_own_payments"
  ],
  [USER_ROLES.VENDOR]: [
    "browse_events",
    "browse_marketplace",
    "book_vendor",
    "create_marketplace_listing",
    "manage_own_storefront",
    "create_marketplace_product",
    "edit_own_marketplace_product",
    "featured_storefront",
    "manage_listing",
    "view_orders",
    "view_earnings",
    "receive_quote_requests",
    "sell_marketplace_item",
    "request_quote",
    "manage_own_listing",
    "receive_requests",
    "view_financials",
    "manage_profile",
    "request_payout",
    "view_own_withdrawals",
    "view_vendor_wallet",
    "view_vendor_earnings",
    "manage_vendor_portfolio",
    "view_vendor_reviews",
    "manage_own_marketplace_profile",
    "featured_listing",
    "advanced_vendor_analytics",
    "view_availability",
    "manage_availability",
    "manage_time_slots",
    "detect_booking_conflicts",
    "view_vendor_crm",
    "manage_leads",
    "manage_customers",
    "create_invoices",
    "view_revenue_tracking",
    "manage_followups",
    "manage_customer_notes",
    "export_crm_data",
    "manage_own_storefront",
    "edit_storefront_theme",
    "publish_storefront",
    "view_storefront_analytics",
    "manage_multi_branch_storefronts",
    "preview_ai_storefront_theme",
    "upload_brand_assets",
    "generate_ai_storefront_theme",
    "publish_ai_storefront_theme",
    "customize_storefront_theme",
    "create_event",
    "create_events",
    "manage_own_events",
    "manage_event",
    "manage_guests",
    "view_event_operations_dashboard",
    "manage_live_tasks",
    "view_live_timeline",
    "manage_staff_coordination",
    "make_payment",
    "submit_payment_proof",
    "view_payment_receipt",
    "view_own_payments",
    "submit_milestone_proof",
    "request_withdrawal"
  ],
  [USER_ROLES.EVENT_PLANNER]: [
    "create_event",
    "manage_event",
    "manage_guests",
    "scanner_access",
    "assign_event_roles",
    "sell_event_tickets",
    "browse_events",
    "browse_marketplace",
    "post_memory",
    "like",
    "comment",
    "share",
    "view_gallery",
    "create_events",
    "manage_own_events",
    "manage_guest_list",
    "post_memories",
    "view_event_analytics",
    "view_qr",
    "manage_profile",
    "request_payout",
    "view_own_withdrawals",
    "review_vendor",
    "book_vendor",
    "view_availability",
    "manage_availability",
    "manage_time_slots",
    "view_availability",
    "manage_staff_schedule",
    "detect_booking_conflicts",
    "view_vendor_crm",
    "manage_leads",
    "manage_customers",
    "create_invoices",
    "manage_followups",
    "manage_customer_notes",
    "preview_ai_storefront_theme",
    "upload_brand_assets",
    "create_marketplace_listing",
    "manage_own_storefront",
    "create_marketplace_product",
    "edit_own_marketplace_product",
    "edit_storefront_theme",
    "publish_storefront",
    "view_storefront_analytics",
    "sell_marketplace_item",
    "manage_own_listing",
    "view_vendor_wallet",
    "view_vendor_earnings",
    "manage_vendor_portfolio",
    "view_vendor_reviews",
    "manage_own_marketplace_profile",
    "make_payment",
    "submit_payment_proof",
    "view_payment_receipt",
    "view_own_payments",
    "approve_milestones"
  ],
  [USER_ROLES.ENTERPRISE_CLIENT]: [
    "create_event",
    "assign_company_users",
    "bulk_invite_guests",
    "approve_team_events",
    "enterprise_billing",
    "browse_events",
    "browse_marketplace",
    "post_memory",
    "like",
    "comment",
    "share",
    "view_gallery",
    "create_events",
    "manage_own_events",
    "manage_guest_list",
    "post_memories",
    "view_event_analytics",
    "view_qr",
    "manage_profile",
    "request_payout",
    "view_company_withdrawals",
    "review_vendor",
    "book_vendor",
    "view_vendor_crm",
    "manage_leads",
    "manage_customers",
    "create_invoices",
    "view_revenue_tracking",
    "manage_followups",
    "manage_customer_notes",
    "export_crm_data",
    "team_crm_access",
    "preview_ai_storefront_theme",
    "upload_brand_assets",
    "generate_ai_storefront_theme",
    "publish_ai_storefront_theme",
    "customize_storefront_theme",
    "remove_invitegenie_branding",
    "manage_multi_branch_themes",
    "create_marketplace_listing",
    "manage_own_storefront",
    "create_marketplace_product",
    "edit_own_marketplace_product",
    "edit_storefront_theme",
    "publish_storefront",
    "view_storefront_analytics",
    "sell_marketplace_item",
    "manage_own_listing",
    "view_vendor_wallet",
    "view_vendor_earnings",
    "manage_vendor_portfolio",
    "view_vendor_reviews",
    "manage_own_marketplace_profile",
    "manage_event",
    "manage_guests",
    "make_payment",
    "submit_payment_proof",
    "view_payment_receipt",
    "view_own_payments"
  ],
  [USER_ROLES.TASKER]: [
    "create_marketplace_listing",
    "manage_own_storefront",
    "create_marketplace_product",
    "edit_own_marketplace_product",
    "accept_tasks",
    "complete_tasks",
    "receive_payouts",
    "browse_events",
    "browse_marketplace",
    "request_quote",
    "view_financials",
    "manage_profile",
    "request_payout",
    "view_own_withdrawals",
    "view_vendor_wallet",
    "view_vendor_earnings",
    "manage_vendor_portfolio",
    "view_availability",
    "manage_availability",
    "view_vendor_crm",
    "manage_leads",
    "manage_customers",
    "manage_customer_notes",
    "create_event",
    "create_events",
    "manage_own_events",
    "manage_event",
    "manage_guests",
    "make_payment",
    "submit_payment_proof",
    "view_payment_receipt",
    "view_own_payments",
    "submit_milestone_proof",
    "request_withdrawal"
  ],
  [USER_ROLES.CHECKIN_AGENT]: [
    "scan_qr",
    "validate_ticket",
    "mark_checked_in",
    "browse_events",
    "scan_event_qr",
    "view_qr",
    "manage_profile",
    "create_marketplace_listing",
    "manage_own_storefront",
    "create_marketplace_product",
    "edit_own_marketplace_product",
    "edit_storefront_theme",
    "publish_storefront",
    "view_storefront_analytics",
    "sell_marketplace_item",
    "manage_own_listing",
    "view_vendor_wallet",
    "view_vendor_earnings",
    "manage_vendor_portfolio",
    "view_vendor_reviews",
    "manage_own_marketplace_profile",
    "create_event",
    "create_events",
    "manage_own_events",
    "manage_event",
    "manage_guests",
    "view_event_operations_dashboard",
    "manage_live_tasks",
    "manage_staff_coordination",
    "trigger_emergency_alerts",
    "manage_vendor_checkin",
    "view_live_timeline"
  ],
  [USER_ROLES.FINANCE_ADMIN]: [
    "view_financials",
    "view_transactions",
    "view_invoices",
    "process_refunds",
    "view_payments",
    "manage_refunds",
    "view_withdrawals",
    "manage_payouts",
    "view_all_vendor_wallets",
    "manage_vendor_payouts",
    "create_marketplace_listing",
    "manage_own_storefront",
    "create_marketplace_product",
    "edit_own_marketplace_product",
    "edit_storefront_theme",
    "publish_storefront",
    "view_storefront_analytics",
    "sell_marketplace_item",
    "manage_own_listing",
    "view_vendor_wallet",
    "view_vendor_earnings",
    "manage_vendor_portfolio",
    "view_vendor_reviews",
    "manage_own_marketplace_profile",
    "create_event",
    "create_events",
    "manage_own_events",
    "manage_event",
    "manage_guests",
    "view_event_operations_dashboard",
    "manage_live_tasks",
    "manage_staff_coordination",
    "trigger_emergency_alerts",
    "manage_vendor_checkin",
    "view_live_timeline",
    "moderate_event_sponsors",
    "view_all_payments",
    "confirm_payments",
    "reject_payments",
    "refund_payments",
    "manage_payment_providers",
    "view_payment_reports"
  ],
  [USER_ROLES.APP_ADMIN]: [
    "manage_users",
    "moderate_feed",
    "moderate_marketplace",
    "moderate_storefronts",
    "approve_marketplace_products",
    "approve_listings",
    "manage_events",
    "view_reports",
    "view_all_users",
    "view_all_events",
    "view_all_marketplace_listings",
    "approve_marketplace_listings",
    "moderate_content",
    "view_withdrawals",
    "manage_payouts",
    "moderate_vendor_profiles",
    "moderate_vendor_reviews",
    "moderate_marketplace",
    "create_marketplace_listing",
    "manage_own_storefront",
    "create_marketplace_product",
    "edit_own_marketplace_product",
    "edit_storefront_theme",
    "publish_storefront",
    "view_storefront_analytics",
    "sell_marketplace_item",
    "manage_own_listing",
    "view_vendor_wallet",
    "view_vendor_earnings",
    "manage_vendor_portfolio",
    "view_vendor_reviews",
    "manage_own_marketplace_profile",
    "create_event",
    "create_events",
    "manage_own_events",
    "manage_event",
    "manage_guests",
    "view_event_operations_dashboard",
    "manage_live_tasks",
    "manage_staff_coordination",
    "trigger_emergency_alerts",
    "manage_vendor_checkin",
    "view_live_timeline",
    "view_command_center",
    "moderate_event_sponsors",
    "view_all_payments",
    "confirm_payments",
    "reject_payments",
    "refund_payments",
    "manage_payment_providers",
    "manage_finance_settings",
    "view_payment_reports"
  ],
  [USER_ROLES.SUPER_ADMIN]: [
    "all_permissions",
    "manage_roles",
    "assign_permissions",
    "manage_admins",
    "platform_settings",
    "audit_logs",
    "manage_pricing",
    "manage_payout_settings",
    "manage_commissions",
    "manage_all_storefronts",
    "manage_featured_storefronts",
    "moderate_storefronts",
    "approve_marketplace_products",
    "manage_all_events",
    "manage_all_marketplace",
    "manage_all_vendor_wallets",
    "manage_all_vendor_profiles",
    "manage_vendor_commissions",
    "create_admin_role",
    "edit_admin_role",
    "delete_admin_role",
    "assign_admin_role",
    "revoke_admin_role",
    "create_permission",
    "edit_permission",
    "delete_permission",
    "view_all_users",
    "view_all_events",
    "view_all_marketplace_listings",
    "approve_marketplace_listings",
    "moderate_content",
    "view_all_financials",
    "manage_platform_settings",
    "manage_commission_rates",
    "manage_2fa_settings",
    "view_audit_logs",
    "manage_multi_location_availability",
    "view_vendor_crm",
    "manage_leads",
    "manage_customers",
    "create_invoices",
    "view_revenue_tracking",
    "manage_followups",
    "manage_customer_notes",
    "export_crm_data",
    "team_crm_access",
    "manage_custom_domain",
    "remove_invitegenie_branding",
    "preview_ai_storefront_theme",
    "upload_brand_assets",
    "generate_ai_storefront_theme",
    "publish_ai_storefront_theme",
    "customize_storefront_theme",
    "manage_multi_branch_themes",
    "view_command_center",
    "manage_multi_event_operations",
    "moderate_event_sponsors",
    "view_all_payments",
    "refund_payments",
    "manage_payment_providers",
    "view_payment_reports"
  ],
};

export const SUPER_ADMIN_PERMISSIONS = ROLE_PERMISSIONS[USER_ROLES.SUPER_ADMIN];

export const ADMIN_PERMISSION_OPTIONS = [
  { id: "manage_users", label: "Manage users", group: "Users" },
  { id: "moderate_feed", label: "Moderate feed", group: "Content" },
  { id: "moderate_marketplace", label: "Moderate marketplace", group: "Marketplace" },
  { id: "moderate_storefronts", label: "Moderate storefronts", group: "Marketplace" },
  { id: "approve_marketplace_products", label: "Approve marketplace products", group: "Marketplace" },
  { id: "manage_all_storefronts", label: "Manage all storefronts", group: "Marketplace" },
  { id: "manage_featured_storefronts", label: "Manage featured storefronts", group: "Marketplace" },
  { id: "approve_listings", label: "Approve listings", group: "Marketplace" },
  { id: "moderate_vendor_profiles", label: "Moderate vendor profiles", group: "Marketplace" },
  { id: "moderate_vendor_reviews", label: "Moderate vendor reviews", group: "Marketplace" },
  { id: "manage_all_vendor_profiles", label: "Manage all vendor profiles", group: "Marketplace" },
  { id: "manage_events", label: "Manage events", group: "Events" },
  { id: "view_reports", label: "View reports", group: "Reports" },
  { id: "manage_availability", label: "Manage Availability", group: "Scheduling" },
  { id: "detect_booking_conflicts", label: "Detect Conflicts", group: "Scheduling" },
  { id: "manage_staff_schedule", label: "Manage Staff Schedule", group: "Scheduling" },
  { id: "manage_multi_location_availability", label: "Manage Multi-location", group: "Scheduling" },
  { id: "view_financials", label: "View financials", group: "Finance" },
  { id: "view_transactions", label: "View transactions", group: "Finance" },
  { id: "view_withdrawals", label: "View withdrawals", group: "Finance" },
  { id: "manage_payouts", label: "Manage payouts", group: "Finance" },
  { id: "view_all_vendor_wallets", label: "View all vendor wallets", group: "Finance" },
  { id: "manage_vendor_payouts", label: "Manage vendor payouts", group: "Finance" },
  { id: "manage_all_vendor_wallets", label: "Manage all vendor wallets", group: "Finance" },
  { id: "manage_payout_settings", label: "Manage payout settings", group: "Platform" },
  { id: "view_invoices", label: "View invoices", group: "Finance" },
  { id: "process_refunds", label: "Process refunds", group: "Finance" },
  { id: "view_payments", label: "View payments", group: "Finance" },
  { id: "manage_pricing", label: "Manage pricing", group: "Platform" },
  { id: "manage_commissions", label: "Manage commissions", group: "Platform" },
  { id: "manage_roles", label: "Manage roles", group: "Roles" },
  { id: "assign_permissions", label: "Assign permissions", group: "Roles" },
  { id: "manage_admins", label: "Manage admins", group: "Roles" },
  { id: "platform_settings", label: "Platform settings", group: "Platform" },
  { id: "audit_logs", label: "Audit logs", group: "Security" },
  { id: "create_admin_role", label: "Create admin roles", group: "Legacy Admin Roles" },
  { id: "edit_admin_role", label: "Edit admin roles", group: "Legacy Admin Roles" },
  { id: "delete_admin_role", label: "Delete admin roles", group: "Legacy Admin Roles" },
  { id: "assign_admin_role", label: "Assign admin roles", group: "Legacy Admin Roles" },
  { id: "view_all_users", label: "View all users", group: "Legacy Users" },
  { id: "view_all_events", label: "View all events", group: "Legacy Events" },
  { id: "view_all_financials", label: "View all financials", group: "Legacy Finance" },
  { id: "approve_marketplace_listings", label: "Approve marketplace listings", group: "Legacy Marketplace" },
  { id: "view_audit_logs", label: "View audit logs", group: "Legacy Audit" },
  { id: "view_vendor_crm", label: "View Vendor CRM", group: "CRM" },
  { id: "manage_leads", label: "Manage Leads", group: "CRM" },
  { id: "manage_customers", label: "Manage Customers", group: "CRM" },
  { id: "create_invoices", label: "Create Invoices", group: "CRM" },
  { id: "view_revenue_tracking", label: "View Revenue Tracking", group: "CRM" },
  { id: "manage_followups", label: "Manage Follow-ups", group: "CRM" },
  { id: "manage_customer_notes", label: "Manage Customer Notes", group: "CRM" },
  { id: "export_crm_data", label: "Export CRM Data", group: "CRM" },
  { id: "team_crm_access", label: "Team CRM Access", group: "CRM" },
  { id: "view_event_operations_dashboard", label: "View Operations Dashboard", group: "Events" },
  { id: "manage_live_tasks", label: "Manage Live Tasks", group: "Events" },
  { id: "manage_staff_coordination", label: "Manage Staff Coordination", group: "Events" },
  { id: "trigger_emergency_alerts", label: "Trigger Emergency Alerts", group: "Events" },
  { id: "manage_vendor_checkin", label: "Manage Vendor Check-in", group: "Events" },
  { id: "view_command_center", label: "View Command Center", group: "Events" },
  { id: "moderate_event_sponsors", label: "Moderate Event Sponsors", group: "Events" },
];

export const DEFAULT_ADMIN_ROLES = [
  {
    id: USER_ROLES.APP_ADMIN,
    name: USER_ROLES.APP_ADMIN,
    label: "App Admin",
    description: "General platform operator with user, event, marketplace, and moderation access.",
    permissions: ROLE_PERMISSIONS[USER_ROLES.APP_ADMIN],
  },
  {
    id: USER_ROLES.FINANCE_ADMIN,
    name: USER_ROLES.FINANCE_ADMIN,
    label: "Finance Admin",
    description: "Owns financial visibility, invoices, payments, refunds, and reports.",
    permissions: ROLE_PERMISSIONS[USER_ROLES.FINANCE_ADMIN],
  },
  {
    id: USER_ROLES.SUPER_ADMIN,
    name: USER_ROLES.SUPER_ADMIN,
    label: "Super Admin",
    description: "Platform owner with role, permission, pricing, commission, and global data control.",
    permissions: ROLE_PERMISSIONS[USER_ROLES.SUPER_ADMIN],
  },
];

export const ROLE_DASHBOARD_TOOLS = {
  [USER_ROLES.NORMAL_USER]: [
    { label: "Browse Events", path: "/events", icon: "event" },
    { label: "My Tickets", path: "/my-tickets", icon: "confirmation_number" },
    { label: "My Gallery", path: "/gallery", icon: "photo_library" },
    { label: "Feed", path: "/feed", icon: "dynamic_feed" },
    { label: "Marketplace", path: "/marketplace", icon: "storefront" },
    { label: "My Storefront", path: "/marketplace/new", icon: "store" },
    { label: "Create Listing", path: "/marketplace/new", icon: "add_business" },
    { label: "Create Event", path: "/events/new", icon: "add_circle" },
    { label: "AI Planner", path: "/ai-planner", icon: "auto_awesome" },
    { label: "Availability", path: "/availability", icon: "calendar_month" },
    { label: "Vendor CRM", path: "/vendor-crm", icon: "contact_page" },
  ],
  [USER_ROLES.PRO_USER]: [
    { label: "Browse Events", path: "/events", icon: "event" },
    { label: "My Tickets", path: "/my-tickets", icon: "confirmation_number" },
    { label: "My Gallery", path: "/gallery", icon: "photo_library" },
    { label: "Feed", path: "/feed", icon: "dynamic_feed" },
    { label: "Marketplace", path: "/marketplace", icon: "storefront" },
    { label: "Saved Events", path: "/events?saved=true", icon: "bookmark" },
    { label: "My Storefront", path: "/marketplace/new", icon: "store" },
    { label: "Create Listing", path: "/marketplace/new", icon: "add_business" },
    { label: "Create Event", path: "/events/new", icon: "add_circle" },
    { label: "AI Planner", path: "/ai-planner", icon: "auto_awesome" },
    { label: "Premium Templates", path: "/templates", icon: "workspace_premium" },
    { label: "Advanced Gallery", path: "/gallery", icon: "auto_awesome_motion" },
    { label: "Priority Support", path: "/support", icon: "support_agent" },
    { label: "Vendor CRM", path: "/vendor-crm", icon: "contact_page" },
  ],
  [USER_ROLES.VENDOR]: [
    { label: "Marketplace Listings", path: "/marketplace", icon: "storefront" },
    { label: "My Storefront", path: "/marketplace/new", icon: "store" },
    { label: "Quote Requests", path: "/dashboard?panel=quotes", icon: "request_quote" },
    { label: "Orders", path: "/dashboard?panel=orders", icon: "shopping_bag" },
    { label: "Earnings", path: "/dashboard?panel=earnings", icon: "payments" },
    { label: "Create Listing", path: "/marketplace/new", icon: "add_business" },
    { label: "Create Event", path: "/events/new", icon: "add_circle" },
    { label: "AI Planner", path: "/ai-planner", icon: "auto_awesome" },
    { label: "Availability", path: "/availability", icon: "calendar_month" },
    { label: "Vendor CRM", path: "/vendor-crm", icon: "contact_page" },
  ],
  [USER_ROLES.EVENT_PLANNER]: [
    { label: "Create Event", path: "/events/new", icon: "add_circle" },
    { label: "Guests", path: "/guests", icon: "groups" },
    { label: "Bookings", path: "/bookings", icon: "confirmation_number" },
    { label: "Scanner", path: "/scanner", icon: "qr_code_scanner" },
    { label: "Event Analytics", path: "/analytics", icon: "analytics" },
    { label: "AI Planner", path: "/ai-planner", icon: "auto_awesome" },
    { label: "Marketplace Requests", path: "/marketplace", icon: "request_quote" },
    { label: "My Storefront", path: "/marketplace/new", icon: "store" },
    { label: "Create Listing", path: "/marketplace/new", icon: "add_business" },
    { label: "Assign Team Roles", path: "/dashboard?panel=event-team", icon: "manage_accounts" },
    { label: "Availability", path: "/availability", icon: "calendar_month" },
    { label: "Vendor CRM", path: "/vendor-crm", icon: "contact_page" },
  ],
  [USER_ROLES.ENTERPRISE_CLIENT]: [
    { label: "Company Events", path: "/events", icon: "corporate_fare" },
    { label: "Team Members", path: "/dashboard?panel=team", icon: "groups" },
    { label: "Reports", path: "/reports", icon: "summarize" },
    { label: "Approvals", path: "/dashboard?panel=approvals", icon: "approval" },
    { label: "Billing", path: "/billing", icon: "receipt_long" },
    { label: "Assign Company Users", path: "/dashboard?panel=company-users", icon: "manage_accounts" },
    { label: "My Storefront", path: "/marketplace/new", icon: "store" },
    { label: "Create Listing", path: "/marketplace/new", icon: "add_business" },
    { label: "Create Event", path: "/events/new", icon: "add_circle" },
    { label: "AI Planner", path: "/ai-planner", icon: "auto_awesome" },
    { label: "Availability", path: "/availability", icon: "calendar_month" },
    { label: "Vendor CRM", path: "/vendor-crm", icon: "contact_page" },
  ],
  [USER_ROLES.TASKER]: [
    { label: "Task Listings", path: "/tasks", icon: "task_alt" },
    { label: "My Storefront", path: "/marketplace/new", icon: "store" },
    { label: "Active Jobs", path: "/tasks?status=active", icon: "work" },
    { label: "Earnings", path: "/dashboard?panel=earnings", icon: "payments" },
    { label: "Marketplace Profile", path: "/marketplace/new", icon: "badge" },
    { label: "Create Event", path: "/events/new", icon: "add_circle" },
    { label: "AI Planner", path: "/ai-planner", icon: "auto_awesome" },
    { label: "Availability", path: "/availability", icon: "calendar_month" },
    { label: "Vendor CRM", path: "/vendor-crm", icon: "contact_page" },
  ],
  [USER_ROLES.CHECKIN_AGENT]: [
    { label: "Scanner", path: "/scanner", icon: "qr_code_scanner" },
    { label: "Today's Events", path: "/events", icon: "today" },
    { label: "Checked-in Guests", path: "/guests", icon: "how_to_reg" },
    { label: "Validation Logs", path: "/dashboard?panel=validation-logs", icon: "fact_check" },
    { label: "My Storefront", path: "/marketplace/new", icon: "store" },
    { label: "Create Listing", path: "/marketplace/new", icon: "add_business" },
    { label: "Create Event", path: "/events/new", icon: "add_circle" },
  ],
  [USER_ROLES.FINANCE_ADMIN]: [
    { label: "Financials", path: "/admin/financials", icon: "payments" },
    { label: "Invoices", path: "/admin/financials?tab=invoices", icon: "receipt" },
    { label: "Payments", path: "/admin/financials?tab=payments", icon: "account_balance_wallet" },
    { label: "Refunds", path: "/admin/financials?tab=refunds", icon: "currency_exchange" },
    { label: "Reports", path: "/admin", icon: "summarize" },
    { label: "My Storefront", path: "/marketplace/new", icon: "store" },
    { label: "Create Listing", path: "/marketplace/new", icon: "add_business" },
    { label: "Create Event", path: "/events/new", icon: "add_circle" },
  ],
  [USER_ROLES.APP_ADMIN]: [
    { label: "Users", path: "/admin/users", icon: "group" },
    { label: "Events", path: "/admin/events", icon: "event_available" },
    { label: "Storefront Moderation", path: "/admin/marketplace", icon: "storefront" },
    { label: "Reports", path: "/admin", icon: "summarize" },
    { label: "My Storefront", path: "/marketplace/new", icon: "store" },
    { label: "Create Listing", path: "/marketplace/new", icon: "add_business" },
    { label: "Create Event", path: "/events/new", icon: "add_circle" },
  ],
  [USER_ROLES.SUPER_ADMIN]: [
    { label: "Everything", path: "/admin/super", icon: "workspace_premium" },
    { label: "Admin Roles", path: "/admin/roles", icon: "admin_panel_settings" },
    { label: "Permissions", path: "/admin/permissions", icon: "key" },
    { label: "Storefront Moderation", path: "/admin/marketplace", icon: "storefront" },
    { label: "Audit Logs", path: "/admin/audit-logs", icon: "manage_search" },
    { label: "Pricing", path: "/admin/pricing", icon: "sell" },
    { label: "Commissions", path: "/admin/financials", icon: "percent" },
    { label: "My Storefront", path: "/marketplace/new", icon: "store" },
    { label: "Create Listing", path: "/marketplace/new", icon: "add_business" },
    { label: "Create Event", path: "/events/new", icon: "add_circle" },
  ],
};

export function normalizePermissions(value) {
  if (Array.isArray(value)) return value.filter(Boolean);
  if (typeof value === "string") {
    try {
      return normalizePermissions(JSON.parse(value));
    } catch {
      return value.split(",").map((item) => item.trim()).filter(Boolean);
    }
  }
  if (typeof value === "object" && value !== null) {
    if (Array.isArray(value.permissions)) return normalizePermissions(value.permissions);
    return Object.entries(value)
      .filter(([, enabled]) => Boolean(enabled))
      .map(([permission]) => permission);
  }
  return [];
}

export function getRolePermissions(role) {
  return ROLE_PERMISSIONS[normalizeRole(role)] || [];
}

export function getPermissionsForProfile(profileOrRole) {
  if (!profileOrRole) return [];
  if (typeof profileOrRole === "string") return getRolePermissions(profileOrRole);
  
  const role = normalizeRole(profileOrRole?.role || profileOrRole?.admin_role);
  const rolePermissions = getRolePermissions(role);
  const profilePermissions = normalizePermissions(profileOrRole?.permissions);
  
  const merged = Array.from(new Set([...rolePermissions, ...profilePermissions]));
  return merged.includes("all_permissions") ? SUPER_ADMIN_PERMISSIONS : merged;
}

export function hasPermission(profileOrRole, permission) {
  const permissions = getPermissionsForProfile(profileOrRole);
  return permissions.includes("all_permissions") || permissions.includes(permission);
}

export function hasAnyPermission(user, permissions = []) {
  return permissions.some((permission) => hasPermission(user, permission));
}

export function getDashboardToolsForRole(role) {
  return ROLE_DASHBOARD_TOOLS[normalizeRole(role)] || ROLE_DASHBOARD_TOOLS.normal_user;
}

/**
 * Specific Capability Policies
 */
export function canCreateMarketplaceListing(profileOrRole) {
  return hasPermission(profileOrRole, "create_marketplace_listing");
}
export function canCreateEvent(profileOrRole) {
  return hasPermission(profileOrRole, "create_event");
}
export function canViewFinancials(profileOrRole) {
  return hasPermission(profileOrRole, "view_financials") || hasPermission(profileOrRole, "view_all_financials");
}
export function canViewAdmin(profileOrRole) {
  const role = typeof profileOrRole === "string" ? profileOrRole : profileOrRole?.role;
  return isAdminRole(role);
}
