/**
 * Canonical User Roles for InviteGenie - The Foundation Layer.
 */
export const USER_ROLES = {
  FREE: "FREE",
  PRO: "PRO",
  BUSINESS: "BUSINESS",
  ENTERPRISE: "ENTERPRISE",
  NORMAL_USER: "FREE",
  PRO_USER: "PRO",
  VENDOR: "BUSINESS",
  EVENT_PLANNER: "PRO",
  ENTERPRISE_CLIENT: "ENTERPRISE",
  TASKER: "FREE",
  CHECKIN_AGENT: "FREE",
  FINANCE_ADMIN: "finance_admin",
  APP_ADMIN: "app_admin",
  SUPER_ADMIN: "super_admin",

  PUBLIC_GUEST: "FREE",
  BASIC_USER: "FREE",
  EVENT_HOST: "PRO",
  VENDOR_BASIC: "BUSINESS",
  VENDOR_PRO: "PRO",
  TASKER_FREELANCER: "FREE",
  STAFF: "FREE",
  STAFF_AGENT: "FREE",
  CHECK_IN_AGENT: "FREE",
  CHECKIN_ADMIN: "app_admin",
  ADMIN: "app_admin",
  SUPPORT_ADMIN: "app_admin",
  MARKETPLACE_ADMIN: "app_admin",
  CONTENT_MODERATOR: "app_admin",
};

export const NORMAL_USER_ROLES = [
  USER_ROLES.FREE,
  USER_ROLES.PRO,
  USER_ROLES.BUSINESS,
  USER_ROLES.ENTERPRISE,
];

export const ADMIN_ROLES = [
  USER_ROLES.FINANCE_ADMIN,
  USER_ROLES.APP_ADMIN,
  USER_ROLES.SUPER_ADMIN,
];

export const ADMIN_LOGIN_ROLES = ADMIN_ROLES;

const LEGACY_ROLE_MAP = {
  FREE: USER_ROLES.FREE,
  PRO: USER_ROLES.PRO,
  BUSINESS: USER_ROLES.BUSINESS,
  ENTERPRISE: USER_ROLES.ENTERPRISE,
  PUBLIC_GUEST: USER_ROLES.FREE,
  BASIC_USER: USER_ROLES.FREE,
  BASIC: USER_ROLES.FREE,
  NORMAL_USER: USER_ROLES.FREE,
  PRO_USER: USER_ROLES.PRO,
  EVENT_HOST: USER_ROLES.PRO,
  HOST: USER_ROLES.PRO,
  EVENT_PLANNER: USER_ROLES.PRO,
  ENTERPRISE_CLIENT: USER_ROLES.ENTERPRISE,
  VENDOR_BASIC: USER_ROLES.BUSINESS,
  VENDOR_PRO: USER_ROLES.PRO,
  VENDOR: USER_ROLES.BUSINESS,
  TASKER_FREELANCER: USER_ROLES.FREE,
  TASKER: USER_ROLES.FREE,
  STAFF: USER_ROLES.FREE,
  STAFF_AGENT: USER_ROLES.FREE,
  CHECK_IN_AGENT: USER_ROLES.FREE,
  CHECKIN_AGENT: USER_ROLES.FREE,
  CHECKIN_ADMIN: USER_ROLES.APP_ADMIN,
  CHECK_IN_ADMIN: USER_ROLES.APP_ADMIN,
  FINANCE_ADMIN: USER_ROLES.FINANCE_ADMIN,
  SUPPORT_ADMIN: USER_ROLES.APP_ADMIN,
  MARKETPLACE_ADMIN: USER_ROLES.APP_ADMIN,
  CONTENT_MODERATOR: USER_ROLES.APP_ADMIN,
  APP_ADMIN: USER_ROLES.APP_ADMIN,
  ADMIN: USER_ROLES.APP_ADMIN,
  SUPER_ADMIN: USER_ROLES.SUPER_ADMIN,
};

const LEGACY_VALUE_MAP = {
  free: USER_ROLES.FREE,
  pro: USER_ROLES.PRO,
  business: USER_ROLES.BUSINESS,
  enterprise: USER_ROLES.ENTERPRISE,
  normal_user: USER_ROLES.FREE,
  basic_user: USER_ROLES.FREE,
  pro_user: USER_ROLES.PRO,
  event_host: USER_ROLES.PRO,
  event_planner: USER_ROLES.PRO,
  enterprise_client: USER_ROLES.ENTERPRISE,
  vendor: USER_ROLES.BUSINESS,
  vendor_basic: USER_ROLES.BUSINESS,
  vendor_pro: USER_ROLES.PRO,
  tasker_freelancer: USER_ROLES.FREE,
  tasker: USER_ROLES.FREE,
  staff: USER_ROLES.FREE,
  staff_agent: USER_ROLES.FREE,
  check_in_agent: USER_ROLES.FREE,
  checkin_agent: USER_ROLES.FREE,
  checkin_admin: USER_ROLES.APP_ADMIN,
  support_admin: USER_ROLES.APP_ADMIN,
  marketplace_admin: USER_ROLES.APP_ADMIN,
  content_moderator: USER_ROLES.APP_ADMIN,
  admin: USER_ROLES.APP_ADMIN,
};

export function normalizeRole(role) {
  if (!role) return USER_ROLES.NORMAL_USER;
  const raw = String(role).trim();
  if (Object.values(USER_ROLES).includes(raw)) return raw;
  if (LEGACY_VALUE_MAP[raw]) return LEGACY_VALUE_MAP[raw];
  return LEGACY_ROLE_MAP[raw.toUpperCase()] || raw.toLowerCase();
}

export function isAdminRole(role) {
  const normalized = normalizeRole(role);
  return ADMIN_ROLES.includes(normalized);
}

export function isNormalUserRole(role) {
  const normalized = normalizeRole(role);
  return NORMAL_USER_ROLES.includes(normalized);
}
