export const NAV_ITEMS = [
  // Main
  { label: "Dashboard", path: "/dashboard", icon: "dashboard", category: "main", requiredPermission: "browse_events" },
  { label: "Events", path: "/events", icon: "event", category: "main", requiredPermission: "browse_events", activePaths: ["/events/"] },
  { label: "Create Event", path: "/events/new", icon: "add_circle", category: "main", requiredPermission: "create_event" },
  { label: "Marketplace", path: "/marketplace", icon: "storefront", category: "main", requiredPermission: "browse_marketplace", activePaths: ["/marketplace/"] },
  { label: "Create Listing", path: "/marketplace/new", icon: "add_business", category: "main", requiredPermission: "create_marketplace_listing" },
  { label: "Create Invitation", path: "/create-invitation", icon: "edit_square", category: "main", requiredPermission: "create_events", minTier: "PRO" },
  { label: "Invitation Templates", path: "/invitations/templates", icon: "dashboard_customize", category: "main", requiredPermission: "create_events" },
  { label: "Templates", path: "/templates", icon: "view_carousel", category: "main", requiredPermission: "create_events" },
  { label: "My Templates", path: "/my-templates", icon: "view_quilt", category: "main", requiredPermission: "manage_own_events", minTier: "PRO" },
  { label: "My Tickets", path: "/my-tickets", icon: "confirmation_number", category: "main", requiredPermission: "view_qr" },
  { label: "Bookings", path: "/bookings", icon: "fact_check", category: "main", requiredPermission: "view_bookings", activePaths: ["/bookings/"] },
  { label: "Global Feed", path: "/feed", icon: "rss_feed", category: "main", requiredPermission: "browse_events" },
  { label: "Upload Memory", path: "/feed/upload", icon: "add_photo_alternate", category: "main", requiredPermission: "post_memories" },
  { label: "Gallery", path: "/gallery", icon: "photo_library", category: "main", requiredPermission: "browse_events" },
  { label: "Calendar", path: "/calendar", icon: "calendar_month", category: "main", requiredPermission: "browse_events" },
  { label: "Inbox", path: "/inbox", icon: "inbox", category: "main", requiredPermission: "manage_profile" },
  { label: "Guests", path: "/guests", icon: "groups", category: "main", requiredPermission: "manage_guest_list" },
  { label: "Guest Management", path: "/guest-management", icon: "group_add", category: "main", requiredPermission: "manage_guest_list" },
  { label: "Scanner", path: "/scanner", icon: "qr_code_scanner", category: "main", requiredPermission: "scan_qr" },
  
  // Business
  { label: "Vendor Insights", path: "/vendor-insights", icon: "insights", category: "business", requiredPermission: ["view_vendor_insights", "advanced_vendor_insights"] },
  { label: "Vendor Genie", path: "/vendor-genie", icon: "auto_awesome", category: "business", requiredPermission: ["use_vendor_genie", "manage_ai_vendor_tools"] },
  { label: "Withdrawals", path: "/withdrawals", icon: "account_balance", category: "business", requiredPermission: ["view_own_withdrawals", "view_company_withdrawals", "view_withdrawals", "manage_payouts"] },
  { label: "Payments", path: "/payments", icon: "payments", category: "business", requiredPermission: "view_financials", minTier: "PRO" },
  { label: "Payment Methods", path: "/payment-methods", icon: "credit_card", category: "business", requiredPermission: "manage_profile" },
  { label: "Subscription & Billing", path: "/billing", icon: "receipt_long", category: "business", requiredPermission: "manage_profile" },
  { label: "Financials", path: "/financials", icon: "monitoring", category: "business", requiredPermission: "view_financials", minTier: "PRO" },
  { label: "Reports", path: "/reports", icon: "bar_chart", category: "business", requiredPermission: "view_event_analytics", minTier: "PRO" },
  { label: "Analytics", path: "/analytics", icon: "analytics", category: "business", requiredPermission: "view_event_analytics", minTier: "PRO" },
  { label: "Invoices", path: "/invoices", icon: "request_quote", category: "business", requiredPermission: "view_invoices", minTier: "PRO" },
  { label: "Integrations", path: "/integrations", icon: "hub", category: "business", requiredPermission: "manage_own_events", minTier: "BUSINESS" },
  { label: "Venue Builder", path: "/venue-builder", icon: "architecture", category: "business", requiredPermission: "manage_own_events", minTier: "PRO" },
  { label: "Vendor Wallet", path: "/vendor-wallet", icon: "account_balance_wallet", category: "business", requiredPermission: "view_vendor_wallet" },
  { label: "Vendor Portfolio", path: "/vendor-portfolio", icon: "cases", category: "business", requiredPermission: "manage_vendor_portfolio" },
  
  // Admin
  { label: "Users Management", path: "/users-management", icon: "group", category: "admin", requiredPermission: "manage_users", minTier: "GOD_MODE" },
  { label: "Vendor Management", path: "/admin/vendors", icon: "store", category: "admin", requiredPermission: "manage_vendors", minTier: "GOD_MODE" },
  { label: "Events Management", path: "/events-management", icon: "event_available", category: "admin", requiredPermission: "manage_events", minTier: "GOD_MODE" },
  { label: "Vendors Management", path: "/vendors-management", icon: "store", category: "admin", requiredPermission: "moderate_marketplace", minTier: "GOD_MODE" },
  { label: "Finance Management", path: "/finance-management", icon: "account_balance_wallet", category: "admin", requiredPermission: "view_financials", minTier: "GOD_MODE" },
  { label: "Content Moderation", path: "/content-moderation", icon: "shield", category: "admin", requiredPermission: "moderate_content", minTier: "GOD_MODE" },
  { label: "Vendor Reviews", path: "/admin/vendor-reviews", icon: "reviews", category: "admin", requiredPermission: "moderate_vendor_reviews", minTier: "GOD_MODE" },
  { label: "Vendor Wallets", path: "/admin/vendor-wallets", icon: "account_balance_wallet", category: "admin", requiredPermission: "manage_all_vendor_wallets", minTier: "GOD_MODE" },
  { label: "Vendor Profiles", path: "/admin/vendor-profiles", icon: "store", category: "admin", requiredPermission: "manage_all_vendor_profiles", minTier: "GOD_MODE" },
  { label: "Support Management", path: "/support-management", icon: "support_agent", category: "admin", requiredPermission: "resolve_support", minTier: "STAFF" },
  { label: "Platform Settings", path: "/platform-settings", icon: "admin_panel_settings", category: "admin", requiredPermission: "manage_platform_settings", minTier: "GOD_MODE" },
  { label: "System Audit Log", path: "/system-audit-log", icon: "manage_search", category: "admin", requiredPermission: "manage_platform_settings", minTier: "GOD_MODE" },
  
  // Genie / Fun
  { label: "Convert Points", path: "/convert-points", icon: "redeem", category: "genie", requiredPermission: "manage_profile" },
  { label: "Make a Wish", path: "/make-a-wish", icon: "auto_awesome", category: "genie", requiredPermission: "manage_profile" },
  { label: "Summon a Genie", path: "/summon-genie", icon: "magic_button", category: "genie", requiredPermission: "browse_events" },
  { label: "Genie Assistant", path: "/genie", icon: "auto_awesome", category: "genie", requiredPermission: "browse_events" },
  
  // Account
  { label: "Wallet", path: "/wallet", icon: "account_balance_wallet", category: "account", requiredPermission: ["view_wallet", "view_vendor_wallet", "view_all_wallets"] },
  { label: "Profile", path: "/profile", icon: "person", category: "account", requiredPermission: "manage_profile" },
  { label: "My Account", path: "/my-account", icon: "manage_accounts", category: "account", requiredPermission: "manage_profile" },
  { label: "Notifications", path: "/notifications", icon: "notifications_active", category: "account", requiredPermission: "manage_profile" },
  { label: "Notification Settings", path: "/notification-settings", icon: "notifications", category: "account", requiredPermission: "manage_profile" },
  { label: "Tasks", path: "/tasks", icon: "task_alt", category: "account", requiredPermission: "manage_profile" },
  { label: "Meetings", path: "/meetings", icon: "groups_2", category: "account", requiredPermission: "manage_profile" },
  { label: "Settings", path: "/settings", icon: "settings", category: "account", requiredPermission: "manage_profile" },
  { label: "Help", path: "/help", icon: "help", category: "account", requiredPermission: "manage_profile" },
  { label: "Support", path: "/support", icon: "support_agent", category: "account", requiredPermission: "manage_profile" },
];

export const CATEGORY_LABELS = {
  main: "Main",
  business: "Business",
  admin: "Admin",
  genie: "Genie Magic",
  account: "Account",
};
