-- Supabase Schema for Invite Genie
-- Run this in your Supabase Dashboard -> SQL Editor

-- Enable UUID extension for primary keys
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Profiles Table
-- Stores user profiles, linked to Supabase Auth.
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name text,
  email text UNIQUE,
  role text DEFAULT 'public_guest', -- e.g., 'public_guest', 'event_host', 'app_admin'
  account_type text DEFAULT 'user', -- e.g., 'user', 'vendor', 'freelancer'
  avatar_url text,
  phone text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- 2. Events Table
-- Stores event details created by hosts.
CREATE TABLE IF NOT EXISTS public.events (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  host_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  title text NOT NULL,
  description text,
  location text,
  event_date timestamptz,
  event_time text, -- e.g., "19:00"
  price numeric DEFAULT 0,
  total_tickets integer DEFAULT 100,
  available_tickets integer DEFAULT 100,
  tickets_sold integer DEFAULT 0,
  revenue numeric DEFAULT 0,
  status text DEFAULT 'active', -- e.g., 'active', 'draft', 'past', 'cancelled'
  category text, -- e.g., 'Wedding', 'Corporate', 'Concert'
  image_url text, -- Cover image for the event
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- 3. Tickets Table
-- Stores individual ticket records for events.
CREATE TABLE IF NOT EXISTS public.tickets (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  event_id uuid REFERENCES public.events(id) ON DELETE CASCADE,
  user_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  buyer_name text,
  buyer_email text,
  event_name text, -- Denormalized for easier access
  ticket_type text DEFAULT 'Standard', -- e.g., 'Standard', 'VIP', 'Table'
  price numeric DEFAULT 0,
  status text DEFAULT 'valid', -- e.g., 'valid', 'used', 'cancelled'
  qr_value text UNIQUE, -- Value encoded in QR code for check-in
  checked_in_at timestamptz,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- 4. Payments Table
-- Records all payment transactions.
CREATE TABLE IF NOT EXISTS public.payments (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  event_id uuid REFERENCES public.events(id) ON DELETE SET NULL,
  user_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  ticket_id uuid REFERENCES public.tickets(id) ON DELETE SET NULL,
  amount numeric DEFAULT 0,
  currency text DEFAULT 'FCFA',
  method text, -- e.g., 'Mobile Money', 'Card', 'Cash'
  status text DEFAULT 'completed', -- e.g., 'completed', 'pending', 'failed', 'refunded'
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- 5. Invitations Table
-- Stores details about invitations sent.
CREATE TABLE IF NOT EXISTS public.invitations (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  event_id uuid REFERENCES public.events(id) ON DELETE CASCADE,
  host_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  guest_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL, -- If guest is a registered user
  guest_email text,
  guest_name text,
  status text DEFAULT 'sent', -- e.g., 'sent', 'opened', 'viewed', 'rsvp_yes', 'rsvp_no'
  template_id text,
  invitation_url text,
  qr_code_url text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- 6. Invitation Guests Table (for external guests or Google Forms integration)
-- Stores guest details, especially those imported from external sources like Google Forms.
CREATE TABLE IF NOT EXISTS public.invitation_guests (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  event_id uuid REFERENCES public.events(id) ON DELETE CASCADE,
  unique_id text UNIQUE, -- Matches the UID generated by Apps Script or Genie
  guest_id text,         -- GUEST-0001 format (from Apps Script)
  name text,
  email text,
  phone text,
  status text DEFAULT 'Pending', -- e.g., 'Pending', 'Confirmed', 'CheckedIn'
  source text DEFAULT 'Genie', -- 'Genie' or 'GoogleForm'
  total_views integer DEFAULT 0,
  total_downloads integer DEFAULT 0,
  last_activity text, -- e.g., 'EMAIL_SENT 2023-01-01T12:00:00Z'
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- 7. Invitation Logs Table
-- Tracks activities related to invitations (sent, opened, viewed, downloaded).
CREATE TABLE IF NOT EXISTS public.invitation_logs (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  guest_id uuid REFERENCES public.invitation_guests(id) ON DELETE CASCADE,
  event_type text, -- 'email_sent', 'email_open', 'invitation_view', 'invitation_download', 'qr_checkin'
  payload jsonb, -- Additional data related to the log event
  created_at timestamptz DEFAULT now()
);

-- 8. Checkins Table
-- Records when a guest checks into an event.
CREATE TABLE IF NOT EXISTS public.checkins (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  guest_id uuid REFERENCES public.invitation_guests(id) ON DELETE CASCADE,
  event_id uuid REFERENCES public.events(id) ON DELETE CASCADE,
  device_id text,
  ip_address text,
  checked_in_at timestamptz DEFAULT now()
);

-- 9. Memories Table
-- User-generated content (photos/videos) from events.
CREATE TABLE IF NOT EXISTS public.memories (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  event_id uuid REFERENCES public.events(id) ON DELETE CASCADE,
  user_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  caption text,
  media_url text NOT NULL,
  likes integer DEFAULT 0,
  comments_count integer DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- 10. Posts Table (for social feed)
CREATE TABLE IF NOT EXISTS public.posts (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  user_name text,
  content text,
  media_url text,
  event_id uuid REFERENCES public.events(id) ON DELETE SET NULL,
  post_type text DEFAULT 'post', -- 'post', 'memory', 'event', 'gig', 'share'
  likes_count integer DEFAULT 0,
  comments_count integer DEFAULT 0,
  shares_count integer DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- 11. Comments Table (for posts)
CREATE TABLE IF NOT EXISTS public.comments (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  post_id uuid REFERENCES public.posts(id) ON DELETE CASCADE,
  user_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  user_name text,
  text text NOT NULL,
  created_at timestamptz DEFAULT now()
);

-- 12. Galleries Table (for event-specific media)
CREATE TABLE IF NOT EXISTS public.galleries (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  event_id uuid REFERENCES public.events(id) ON DELETE CASCADE,
  media_url text NOT NULL,
  caption text,
  uploaded_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at timestamptz DEFAULT now()
);

-- 13. Vendors Table (for service providers)
CREATE TABLE IF NOT EXISTS public.vendors (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  name text NOT NULL,
  description text,
  category text, -- e.g., 'Caterer', 'Photographer', 'DJ'
  location text,
  contact_email text,
  contact_phone text,
  rating numeric DEFAULT 0,
  jobs_completed integer DEFAULT 0,
  is_verified boolean DEFAULT false,
  profile_image_url text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- 14. Freelancers Table (similar to vendors but for individual professionals)
CREATE TABLE IF NOT EXISTS public.freelancers (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  name text NOT NULL,
  category text, -- e.g., 'Photographer', 'Musician', 'Designer'
  bio text,
  location text,
  hourly_rate numeric DEFAULT 0,
  rating numeric DEFAULT 0,
  is_verified boolean DEFAULT false,
  is_available boolean DEFAULT true,
  profile_image_url text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- 15. Gigs Table (freelancer job postings)
CREATE TABLE IF NOT EXISTS public.gigs (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  host_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  event_id uuid REFERENCES public.events(id) ON DELETE SET NULL,
  title text NOT NULL,
  description text,
  budget numeric DEFAULT 0,
  status text DEFAULT 'open', -- 'open', 'assigned', 'completed', 'cancelled'
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- 16. Freelancer Bookings Table
CREATE TABLE IF NOT EXISTS public.freelancer_bookings (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  gig_id uuid REFERENCES public.gigs(id) ON DELETE CASCADE,
  freelancer_id uuid REFERENCES public.freelancers(id) ON DELETE CASCADE,
  user_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL, -- The user who booked the freelancer
  status text DEFAULT 'pending', -- 'pending', 'confirmed', 'completed', 'cancelled'
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- 17. Seat Maps Table
-- Stores layout data for event seating.
CREATE TABLE IF NOT EXISTS public.seat_maps (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  event_id uuid REFERENCES public.events(id) ON DELETE CASCADE,
  map_data jsonb, -- JSON representation of the seat map layout
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- 18. Guest Assignments Table (for specific seat assignments)
CREATE TABLE IF NOT EXISTS public.guest_assignments (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  event_id uuid REFERENCES public.events(id) ON DELETE CASCADE,
  ticket_id uuid REFERENCES public.tickets(id) ON DELETE CASCADE,
  seat_id text, -- Identifier for the seat (e.g., "Table A, Seat 3")
  assigned_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at timestamptz DEFAULT now()
);

-- Set up Row Level Security (RLS) policies
-- These are basic examples; you'll need to refine them based on your exact access control needs.

-- Enable RLS on all tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invitations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invitation_guests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invitation_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.checkins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.memories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.galleries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vendors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.freelancers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gigs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.freelancer_bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.seat_maps ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.guest_assignments ENABLE ROW LEVEL SECURITY;

-- RLS Policies (Examples - customize as needed)

-- Profiles: Users can view all profiles, but only update their own
CREATE POLICY "Allow all authenticated users to view profiles" ON public.profiles FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Allow users to update their own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Events: Authenticated users can read all active events. Hosts can manage their own events.
CREATE POLICY "Allow authenticated users to view active events" ON public.events FOR SELECT USING (status = 'active' AND auth.role() = 'authenticated');
CREATE POLICY "Allow hosts to manage their own events" ON public.events FOR ALL USING (host_id = auth.uid());

-- Tickets: Users can read their own tickets. Event hosts can read tickets for their events.
CREATE POLICY "Allow users to view their own tickets" ON public.tickets FOR SELECT USING (user_id = auth.uid());
CREATE POLICY "Allow event hosts to view tickets for their events" ON public.tickets FOR SELECT USING (EXISTS (SELECT 1 FROM public.events WHERE events.id = tickets.event_id AND events.host_id = auth.uid()));
CREATE POLICY "Allow authenticated users to create tickets" ON public.tickets FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Payments: Users can read their own payments.
CREATE POLICY "Allow users to view their own payments" ON public.payments FOR SELECT USING (user_id = auth.uid());
CREATE POLICY "Allow authenticated users to create payments" ON public.payments FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Invitations: Users can read invitations sent to them. Hosts can manage invitations for their events.
CREATE POLICY "Allow guests to view their own invitations" ON public.invitations FOR SELECT USING (guest_id = auth.uid() OR guest_email = (SELECT email FROM public.profiles WHERE id = auth.uid()));
CREATE POLICY "Allow hosts to manage invitations for their events" ON public.invitations FOR ALL USING (host_id = auth.uid());

-- Invitation Guests: Hosts can manage guests for their events. Staff can read.
CREATE POLICY "Allow hosts to manage guests for their events" ON public.invitation_guests FOR ALL USING (EXISTS (SELECT 1 FROM public.events WHERE events.id = invitation_guests.event_id AND events.host_id = auth.uid()));
CREATE POLICY "Allow staff to read all invitation guests" ON public.invitation_guests FOR SELECT USING (auth.jwt() ->> 'user_role' = 'staff'); -- Assuming user_role is in JWT claims

-- Invitation Logs: Read-only for hosts of the associated event.
CREATE POLICY "Allow hosts to read invitation logs for their events" ON public.invitation_logs FOR SELECT USING (EXISTS (SELECT 1 FROM public.invitation_guests WHERE invitation_guests.id = invitation_logs.guest_id AND EXISTS (SELECT 1 FROM public.events WHERE events.id = invitation_guests.event_id AND events.host_id = auth.uid())));

-- Checkins: Staff can create checkins. Hosts can read checkins for their events.
CREATE POLICY "Allow staff to create checkins" ON public.checkins FOR INSERT WITH CHECK (auth.jwt() ->> 'user_role' = 'staff');
CREATE POLICY "Allow hosts to read checkins for their events" ON public.checkins FOR SELECT USING (EXISTS (SELECT 1 FROM public.events WHERE events.id = checkins.event_id AND events.host_id = auth.uid()));

-- Memories: All authenticated users can view. Users can create their own.
CREATE POLICY "Allow authenticated users to view memories" ON public.memories FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Allow users to create their own memories" ON public.memories FOR INSERT WITH CHECK (user_id = auth.uid());

-- Posts: All authenticated users can view. Users can create their own.
CREATE POLICY "Allow authenticated users to view posts" ON public.posts FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Allow users to create their own posts" ON public.posts FOR INSERT WITH CHECK (user_id = auth.uid());

-- Comments: All authenticated users can view. Users can create their own.
CREATE POLICY "Allow authenticated users to view comments" ON public.comments FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Allow users to create their own comments" ON public.comments FOR INSERT WITH CHECK (user_id = auth.uid());

-- Galleries: All authenticated users can view. Hosts can upload to their events.
CREATE POLICY "Allow authenticated users to view galleries" ON public.galleries FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Allow hosts to upload to their event galleries" ON public.galleries FOR INSERT WITH CHECK (EXISTS (SELECT 1 FROM public.events WHERE events.id = galleries.event_id AND events.host_id = auth.uid()));

-- Vendors: All authenticated users can view verified vendors. Vendors can manage their own profile.
CREATE POLICY "Allow authenticated users to view verified vendors" ON public.vendors FOR SELECT USING (is_verified = TRUE AND auth.role() = 'authenticated');
CREATE POLICY "Allow vendors to manage their own profile" ON public.vendors FOR ALL USING (user_id = auth.uid());

-- Freelancers: All authenticated users can view verified freelancers. Freelancers can manage their own profile.
CREATE POLICY "Allow authenticated users to view verified freelancers" ON public.freelancers FOR SELECT USING (is_verified = TRUE AND auth.role() = 'authenticated');
CREATE POLICY "Allow freelancers to manage their own profile" ON public.freelancers FOR ALL USING (user_id = auth.uid());

-- Gigs: All authenticated users can view open gigs. Hosts can manage their own gigs.
CREATE POLICY "Allow authenticated users to view open gigs" ON public.gigs FOR SELECT USING (status = 'open' AND auth.role() = 'authenticated');
CREATE POLICY "Allow hosts to manage their own gigs" ON public.gigs FOR ALL USING (host_id = auth.uid());

-- Freelancer Bookings: Users can view their own bookings. Freelancers can view bookings for their gigs.
CREATE POLICY "Allow users to view their own freelancer bookings" ON public.freelancer_bookings FOR SELECT USING (user_id = auth.uid());
CREATE POLICY "Allow freelancers to view bookings for their gigs" ON public.freelancer_bookings FOR SELECT USING (freelancer_id = auth.uid());

-- Seat Maps: Hosts can manage seat maps for their events.
CREATE POLICY "Allow hosts to manage seat maps for their events" ON public.seat_maps FOR ALL USING (EXISTS (SELECT 1 FROM public.events WHERE events.id = seat_maps.event_id AND events.host_id = auth.uid()));

-- Guest Assignments: Hosts can manage guest assignments for their events.
CREATE POLICY "Allow hosts to manage guest assignments for their events" ON public.guest_assignments FOR ALL USING (EXISTS (SELECT 1 FROM public.events WHERE events.id = guest_assignments.event_id AND events.host_id = auth.uid()));

-- Enable update_at trigger for all tables
-- You would typically create a function for this once and apply to all tables
-- Example for one table:
-- CREATE FUNCTION update_updated_at_column()
-- RETURNS TRIGGER AS $$
-- BEGIN
--    NEW.updated_at = NOW();
--    RETURN NEW;
-- END;
-- $$ language 'plpgsql';
-- CREATE TRIGGER update_events_updated_at BEFORE UPDATE ON public.events FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();